REFRESH_TOKEN_EXPIRE_SECONDS = 2592000  # 30 days

REFRESH_TOKEN_EXPIRE_DAYS = 30

ACCESS_TOKEN_EXPIRE_MINS = 20

PASSWORD_MIN_LENGTH = 6

PASSWORD_MAX_LENGTH = 20

NAME_MIN_LENGTH = 2

NAME_MAX_LENGTH = 20

EMAIL_REGEXP = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
