"""Fix incorrect relationships

Revision ID: e194dd689098
Revises: 210c8d1295d0
Create Date: 2026-08-14 10:18:33.170597

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e194dd689098"
down_revision: Union[str, Sequence[str], None] = "210c8d1295d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("refresh_tokens_user_id_fkey"), "refresh_tokens", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "refresh_tokens", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("tasks_user_id_fkey"), "tasks", type_="foreignkey")
    op.create_foreign_key(
        None, "tasks", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("tasks_user_id_fkey"), "tasks", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("refresh_tokens_user_id_fkey"),
        "refresh_tokens",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
